### ISSUE TITLE
Build error due to `penumbra-proof-params` use of Git LFS

### ISSUE THREAD

**Issue by redshiftzero** [penumbra-zone/galileo#29]
Galileo fails to build due to being unable to resolve Git LFS pointers is the dependency `penumbra-proof-params`. This can be seen in [this CI job](https://github.com/penumbra-zone/galileo/actions/runs/4271263235).

@plaidfinch found this issue indicating that Git LFS assets in dependencies is not supported by cargo: https://github.com/rust-lang/cargo/issues/9692

During release of Lysithea (https://github.com/penumbra-zone/penumbra/issues/2005) we temporarily used a path dependency to get galileo to build. 

Another option suggested by @plaidfinch is to use a submodule, which @conorsch volunteered to take a look at.

**Comment by conorsch** [comment]
We plan to use a submodule dependency _for now_, to keep our build infra on the rails. However, a submodule isn't ideal into the future. Part of why we maintain Galileo is that it gives us a perspective on what it's like to build external tools against Penumbra. Now that we're adding zk proofs, we don't want to require third-party developers to submodule-in the dependency. More investigation required for a long-term solution.

**Comment by conorsch** [comment]
We went with a relpath for now, and are able to build successfully again. We'll need to revisit this, but we have a workaround for now.
