### ISSUE TITLE
Update to use new view, wallet APIs

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/galileo#6]
The changes to the wallet architecture have broken the Galileo code, so it needs to be rewritten to match the new architecture.  Fortunately, this should be much easier than before.

The basic shape of the new structure should, initially, look roughly like:

- a `ViewService` that syncs with the chain;
- a `SoftHSM` that stores the spend key;
- a worker task that:
  - waits for the view to sync (once, at the beginning), then
  - listens for new send requests on a mpsc, and for each request:
    - queries the view service for notes to use;
    - builds a transaction plan;
    - signs the transaction plan with the custody service;
    - submits the transaction;
    - waits 6 seconds before processing the next send request, so that the change notes are flushed into the view service.

Because the mpsc sender is clonable, it can be fed by two tasks: one that's responsible for catching up on backlog, and another that's responsible for responding to current requests, or whatever other setup makes sense for the existing architecture.

This is an MVP implementation of the new architecture.  In the future, it could be straightforwardly extended to allow the worker more parallelism and reduced latency, by having the worker keep a (time-limited) cache of notes it may have spent, or by creating custom transaction plans that rebalance its funds across N notes, etc.  But because the code doesn't currently work, we should do the simplest possible thing to get it working again, before extending it.

**Comment by pygmygoats** [comment]
Can also remove the 10 second sleep configuration (?)

**Comment by erwanor** [comment]
@hdevalence Are there remaining TODOs on this issue? I've checked out the repo and could spot `ViewService` as well as the custody wrapper.

**Comment by conorsch** [comment]
Closing as resolved
