### ISSUE TITLE
Galileo gets confused about block height

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/galileo#62]
Saw an interesting failure mode today:

>  `"Worker failed: status: Unavailable, message: "error querying abci: response error\n\nCaused by:\n    Internal error: height 9307 must be less than or equal to the current blockchain height 9306 (code: -32603)\n\nLocation:\n    /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 22 Aug 2023 10:46:17 GMT", "content-length": "0"} }", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} })`

Galileo was stuck, sending that message on every faucet request. Simply bouncing the service via `kubectl rollout restart deployment galileo` was enough to get it working again, but we should figure out how that failure occurred.

**Comment by cronokirby** [comment]
9307 vs 9306: is there an off by 1 somewhere?

**Comment by zbuc** [comment]
Happened again today:

```
(error: status: Internal, message: "Worker failed: status: Unavailable, message: "error querying abci: response error\n\nCaused by:\n    Internal error: height 21659 must be less than or equal to the current blockchain height 21658 (code: -32603)\n\nLocation:\n    /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 23 Aug 2023 06:57:05 GMT", "content-length": "0"} }", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} })
```

@cronokirby maybe but it's weird that it only happens after running successfully for a while. Maybe some kind of race condition in syncing or something, or not syncing to the correct height, or...?

**Comment by zbuc** [comment]
There are two places in our Rust code where the `error querying abci` error can come from, either during `abci_query` or during `get_block_by_height`. So for whatever reason, it seems like galileo is specifying a too-high block height for an ABCI operation.

**Comment by conorsch** [comment]
We saw this drift further today:

> `Failed to send tokens to the following addresses:
penumbrav2t1369s2qhsmhst974wtprspll3r3p7vky2lktn6q79h3qzdzkgz32azk8pjas6zydz25y90a7xhzs2yesk7mzaet6dfq09kt5zjwt7e4sqj74nxqn724z0j895dqektamjqv4k8s (error: status: Internal, message: "Worker failed: status: Unavailable, message: "error querying abci: response error\n\nCaused by:\n    Internal error: height 260895 must be less than or equal to the current blockchain height 260555 (code: -32603)\n\nLocation:\n    /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/flex-error-0.4.4/src/tracer_impl/eyre.rs:10:9", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Fri, 08 Sep 2023 15:10:54 GMT", "content-length": "0"} }", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} })
@radiant @penumbra labs: you may want to investigate this error :)`

That's 330 blocks off. Looks like the nodes backing the TM RPC are out of sync:

```
❯ curl -s https://rpc.testnet.penumbra.zone/status | jq -r .result.sync_info.latest_block_height
262441
❯ curl -s https://rpc.testnet.penumbra.zone/status | jq -r .result.sync_info.latest_block_height
262441
❯ curl -s https://rpc.testnet.penumbra.zone/status | jq -r .result.sync_info.latest_block_height
260556
```

External clients can be connected to one or the other backend node. Those nodes should be in sync. Why aren't they?

**Comment by conorsch** [comment]
Looks like we had heavy load on `fn-0` that caused it to lag behind. Bouncing the fn-0 pod allowed it to catch up, and block heights match. We did _not_ observe divergence from consensus.

**Comment by conorsch** [comment]
There's no change required to Galileo here: the problem was 1) fullnodes getting out of sync and 2) those fullnodes backing the same LB service. We'll continue to improve the deployment logic where possible.
