### ISSUE TITLE
galileo can't pay fees

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/galileo#97]
We recently enabled non-zero fees on Testnet 77 (https://github.com/penumbra-zone/penumbra/issues/4306), and Galileo broke:

> `Jun 04 15:34:39.867 ERROR galileo::responder: Failed to send funds addr=penumbra1nwqfygm9ky55j50pe60shxvvkjwhrs4tec5mjg7qtdzv4dfr3xcsaxxrprwjzjpvvng894k634n7242w6x776awz9c2ut9kujnzye9952pmmn99493g9lm292d8m8kjs2930u3 e=status: Internal, message: "Error submitting transaction: code 1, log: failed to deliver transaction: check_stateful failed: fee must be greater than or equal to the transaction base price (supplied: 0, base: 21216)", details: [], metadata: MetadataMap { headers: {} }`

We should update the Galileo interface so it can submit transactions when fees are enabled.

**Comment by cratelyn** [comment]
closed by #98. fabulous working with you as always, @conorsch!
